spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/bishe11?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=FALSE
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /project
mybatis:
  mapper-locations:
    classpath: mapper/*.xml
  type-aliases-package: com.personal.applocation.pojo
  configuration:
    map-underscore-to-camel-case: true
